### ISSUE TITLE
Midori Web browser

### ISSUE THREAD

**Issue by voidpin** [NetBSD/pkgsrc-wip#10]
Hello people!
I just found out Midori is back from the dead, https://github.com/midori-browser/core
Looking through pkgsrc-wip I found you're still testing the unmaintained upstream version that saw its last update in early 2016.

Wouldn't it be better to shift focus to the new release?
I'm looking at an alternative to Firefox and used to like Midori.

Thx for your time!

**Comment by bsiegert** [comment]
Good idea! Feel free to submit a patch :)

**Comment by voidpin** [comment]
Thanks!
Do you think a patch is enough?
I belive the make file needs to be modified.
I'm not really sure how to proceed!?
I'm new on NetBSD and prior to that I've been using Linux for nearly 2 years.
I'm not an idiot, though ;-)... after all I'm running NetBSD with awesome wm on a laptop :-)
I'll see if it builds on my machine first.

**Comment by voidpin** [comment]
@bsiegert 
Thx for self-assign yourself to this.
But, somehow I feel I should learn how to build and package stuff for NetBSD.

**Comment by krytarowski** [comment]
https://github.com/joyent/pkgsrc/wiki good tutorials on packages

**Comment by bsiegert** [comment]
Unfortunately, this is a bit more involved as an update.

At least, it needs vala support in `wip/gcr`. I am looking into it.

**Comment by iamleot** [comment]
Hello pin,

pin writes:
> Thanks!
> Do you think a patch is enough?
> I belive the make file needs to be modified.
> I'm not really sure how to proceed!?

I suggest to start with wip/midori by removing PKGREVISION and bumping
DISTNAME to the latest stable version and then `make makesum'.
After doing that `make patch' will try to apply the patches but probably
will fail.

patch-CMakeLists.txt probably should be removed and instead
wip/gcr/buildlink3.mk included (see the one at the end).
All the other patches needs further investigation (config/CMakeLists.txt
probably is still needed, all the others were needed for vala-0.42.0
support).


Have fun!

**Comment by bsiegert** [comment]
I just committed a working midori-7.0 :) It needs a few cleanups but I can use it.

**Comment by voidpin** [comment]
@krytarowski 
Thx! I'll read through it. I've created packages for Void before using xbps-src... I'm hoping its similar, since Void was created by Romero inspired by pkgsrc.

@bsiegert 
Yeap, gcr...
Man, that was fast ;o)

@iamleot 
Cheers!

Thank you all of you! Amazing stuff!!!

**Comment by voidpin** [comment]
Giving you guys credit on UnitedBSD forum.
Thanks!!

**Comment by krytarowski** [comment]
The void linux person was a pkgsrc developer.

**Comment by voidpin** [comment]
I've been using Midori 7.0 for a few weeks now. Had to install gcc6-libs for it to work, see this thread https://mail-index.netbsd.org/netbsd-users/2019/01/21/msg022082.html
But, I guess this was related to the building.

Thanks a lot for it!
