### ISSUE TITLE
ufetch

### ISSUE THREAD

**Issue by voidpin** [NetBSD/pkgsrc-wip#12]
As I wanted to have a minimal CLI system information tool on my NetBSD install, I've modified the code in ufetch, https://gitlab.com/jschx/ufetch to make it work on NetBSD.
I've posted this here, https://www.unitedbsd.com/d/14-system-information-on-the-cli-ufetch and got the suggestion to submit it to pkgsrc.
I've created a separated repo on github, https://github.com/voidpin/ufetch-netbsd just for this and if you guys find it's interesting to anyone else, please feel free to use/package it.

Best Regards,
Pedro

P.S./EDIT: It requires the user to have pkgin set-up as it uses 'pkgin list' to fetch the number of packages installed.

**Comment by krytarowski** [comment]
Please upstream local patches for ufetch to upstream repo.

**Comment by voidpin** [comment]
Done, https://gitlab.com/jschx/ufetch/issues/5
Let's wait and see if its merged.
If so, I'll post back here.
Thx and Regards, 
Pedro

**Comment by voidpin** [comment]
Merged into upstream ufetch, https://gitlab.com/jschx/ufetch/commit/91c9ac9acdbe2b96ec95276360615f98cf36b951
