### ISSUE TITLE
Molsketch

### ISSUE THREAD

**Issue by voidpin** [NetBSD/pkgsrc-wip#15]
Hi everyone,
I'm a chemist and would like to have a supported/active 2D molecular editor installed on my NetBSD amd64 machine.
How difficult would be to build and package Molsketch (https://sourceforge.net/projects/molsketch/) for NetBSD? Is it possible? I have no experience in this, but wouldn't mind getting my hands dirty and, at the same time get some experience. chemtool hasn't seen an update since 2013 and BKChem since 2010. These are the tools available on pkgsrc...
Guidance appreciated!
Thanks!

**Comment by iamleot** [comment]
Hello pin,
if you would like start packaging I suggest to dig in `The pkgsrc guide'
and request an account for pkgsrc-wip:

 https://www.pkgsrc.org/wip/users

Usually, to start it's an:

 % cd pkgsrc/wip
 % mkdir <pkg> && cd <pkg>
 % url2pkg <URL>

...and then adjusting the corresponding `Makefile'.

If you get stuck both #pkgsrc IRC channel at Freenode and tech-pkg@ ML
are good places to get more help!


Have fun!

**Comment by voidpin** [comment]
Thx!
I'll dig into it and see how far I get, it would be nice to contribute and maintain a few packades ;)
Back in a week or so, have some reading to do :)

**Comment by voidpin** [comment]
Hi,
Tried to build the package locally, but failed :(
Installed cmake and the qt5-5.13.1 meta-package. Running cmake fails because it can not find the required packages, which from the CMakeList.txt file are the following...
```
 57         set(Qt5RequiredPackages
 58                 Core
 59                 Widgets
 60                 Gui
 61                 PrintSupport
 62                 Svg
 63                 Network
 64         ) 
```
I've tried looking for a different name for these packages, found that Qt5Svg is called qt5svg, but couldn't find Core or the others. Maybe I'm still not advanced enough to start packaging :(

**Comment by voidpin** [comment]
Ok guys, just sharing my experience...
Initially I had problems with checksums. The sourceforge link was not working and the directlink caused a mismatch in the checksums. I've downloaded the .tar.gz file and hosted it on my github under a temporary repository.
This solved the issue with the checksums. Running bmake proceeds fine untill the Qt5 dependencies above are not found :( 
Obviously, the build fails....

**Comment by iamleot** [comment]
Hello @voidpin!
Can you please share the WIP package on pkgsrc-wip and maybe populate a TODO file with the build errors? (also if it still has some prolem it's perfectly fine to share it on pkgsrc-wip!)

In that way it will be easier to investigate/work on it collaboratevily!


Thanks for working on it!

**Comment by voidpin** [comment]
No, thank you for your interest, I've now requested commit access to pkgsrc-wip.
Unfortunately, I've cleaned the build directory, but don't worry, as soon as I have commit access, I'll repeat the procedure and report on the build errors.
Looking forward to learn :) I'm not a programmer....

**Comment by krytarowski** [comment]
I can package it but I am disoriented as inside https://sourceforge.net/projects/molsketch/files/Molsketch/ there are several catalogues like nitrogen, hydrogen.. Please point exact tarball to fetch and package.

**Comment by voidpin** [comment]
The latest release is the one in the Nitrogen folder, 0.6.0. https://sourceforge.net/projects/molsketch/files/Molsketch/Nitrogen%200.6.0/Molsketch-0.6.0-src.tar.gz/download

**Comment by krytarowski** [comment]
Please check: wip/molsketch

It builds, installs and runs for me.

**Comment by voidpin** [comment]
Wow! Amazing, thx!
Call it noob mistake if you wish...
I did figure that you needed `USE_LANGUAGES=	c c++` as initially I had only `c++`
My Makefile was missing these three lines
```
.include "../../biology/openbabel/buildlink3.mk"
.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"

```
:( How did you find this? I'm here to learn and hope to be able to build packages myself soon!
I was obviously, also missing cmake path detection and PLIST, as I didn't get that far...
Let me ask you, was the cmake path expecting Linux or, was it something different?

Once again thank you! I'll be building the package tomorrow as I left my NetBSD machine at work this evening.

Finally, one more **noob** question... should I use `bmake`, `cmake` or just `make` to build the package now that the Makefile is fixed?

**Comment by krytarowski** [comment]
> I did figure that you needed USE_LANGUAGES= c c++ as initially I had only c++

USE_LANGUAGES is typically try and fail.

> How did you find this?

`grep -r Svg ../../x11/qt5*/`

And adding relative path to `buildlink3.mk` of dependencies.

Most of packaging is grepping.

bmake only if you run bootstrap yourself, on NetBSD native make is fine. Never run directly cmake as it is a tool inside a package.

Does molsketch work? If so, I will import it into pkgsrc.

**Comment by voidpin** [comment]
Thank you!
I'll build the package tomorrow morning (Sweden) and let you know.
I'm guessed `qt5-qtsvg`, but couldn't figure that all others were included in `qt5-qtbase`

**Comment by voidpin** [comment]
Trying to build the package. First I had to `ALLOW_VULNERABLE_PACKAGES=` in `mk.conf` to build `libmolsketch`
But later it fails to build `openbabel` with the following
```

===> Building for openbabel-2.3.2nb9
[  0%] Building CXX object src/CMakeFiles/openbabel.dir/alias.o
In file included from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:19:0,
                 from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:17:
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/shared_ptr.h:33:17: error: 'std::tr1' has not been declared
      using std::tr1::shared_ptr;
                 ^
In file included from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:17:0:
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:118:47: error: 'shared_ptr' was not declared in this scope
   typedef std::vector< std::pair<std::string, shared_ptr<OBSmartsPattern> > > SmartsTable;
                                               ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:118:73: error: template argument 2 is invalid
   typedef std::vector< std::pair<std::string, shared_ptr<OBSmartsPattern> > > SmartsTable;
                                                                         ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:118:75: error: template argument 1 is invalid
   typedef std::vector< std::pair<std::string, shared_ptr<OBSmartsPattern> > > SmartsTable;
                                                                           ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:118:75: error: template argument 2 is invalid
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:118:77: error: expected unqualified-id before '>' token
   typedef std::vector< std::pair<std::string, shared_ptr<OBSmartsPattern> > > SmartsTable;
                                                                             ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/alias.h:119:24: error: 'SmartsTable' has not been declared
   static bool LoadFile(SmartsTable& smtable);
                        ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:239:26: error: 'bool OpenBabel::AliasData::LoadFile' is not a static data member of 'class OpenBabel::AliasData'
 bool AliasData::LoadFile(SmartsTable& smtable)
                          ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:239:26: error: 'SmartsTable' was not declared in this scope
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:239:39: error: 'smtable' was not declared in this scope
 bool AliasData::LoadFile(SmartsTable& smtable)
                                       ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:240:1: error: expected ',' or ';' before '{' token
 {
 ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/alias.cpp:396:1: error: expected '}' at end of input
 }//namespace
 ^
*** Error code 1

Stop.
make[2]: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make[2]: stopped in /usr/pkgsrc/biology/openbabel
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/biology/openbabel
*** Error code 1

Stop.
make: stopped in /usr/pkgsrc/wip/molsketch

```

**Comment by krytarowski** [comment]
https://github.com/NetBSD/pkgsrc/blob/trunk/biology/openbabel/Makefile#L14

Please experiment and try to change this line to: gnu++03. If not, report to @jsonn as he added this line.

**Comment by voidpin** [comment]
:( Unfortunately it doesn't work... `openbabel` still fails to build. @jsonn

**Comment by krytarowski** [comment]
https://github.com/openbabel/openbabel/releases/tag/openbabel-3-0-0

Probably the best way forward is to upgrade openbabel to 3.0. The pkgsrc version uses compiler extension for, at that time, unreleased C++ standard.

**Comment by krytarowski** [comment]
I will give it a try.

**Comment by voidpin** [comment]
Great stuff! Thank you so much!!!

**Comment by krytarowski** [comment]
How about building the pkgsrc openbabel with `c gnu++11`? It was already patched for this version.

**Comment by voidpin** [comment]
At least it start the building of `openbabel`, but still fails at 20% with
```

[ 20%] Building CXX object src/CMakeFiles/plugin_ops.dir/ops/sort.o
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp: In member function 'virtual bool OpenBabel::OpSort::ProcessVec(std::vector<OpenBabel::OBBase*>&)':
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:117:99: error: no matching function for call to 'make_pair(OpenBabel::OBBase*&, double)'
       valvec.push_back(std::make_pair<OBBase*,double>(*iter, _pDesc->Predict(*iter, &_pDescOption)));
                                                                                                   ^
In file included from /usr/include/g++/bits/stl_algobase.h:64:0,
                 from /usr/include/g++/bits/char_traits.h:39,
                 from /usr/include/g++/string:40,
                 from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/op.h:23,
                 from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:19:
/usr/include/g++/bits/stl_pair.h:276:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^
/usr/include/g++/bits/stl_pair.h:276:5: note:   template argument deduction/substitution failed:
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:117:99: note:   cannot convert 'iter.__gnu_cxx::__normal_iterator<_Iterator, _Container>::operator*<OpenBabel::OBBase**, std::vector<OpenBabel::OBBase*> >()' (type 'OpenBabel::OBBase*') to type 'OpenBabel::OBBase*&&'
       valvec.push_back(std::make_pair<OBBase*,double>(*iter, _pDesc->Predict(*iter, &_pDescOption)));
                                                                                                   ^
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:147:68: error: no matching function for call to 'make_pair(OpenBabel::OBBase*&, std::string&)'
       valvec.push_back(std::make_pair<OBBase*,std::string>(*iter, s));
                                                                    ^
In file included from /usr/include/g++/bits/stl_algobase.h:64:0,
                 from /usr/include/g++/bits/char_traits.h:39,
                 from /usr/include/g++/string:40,
                 from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/include/openbabel/op.h:23,
                 from /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:19:
/usr/include/g++/bits/stl_pair.h:276:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^
/usr/include/g++/bits/stl_pair.h:276:5: note:   template argument deduction/substitution failed:
     ^
/usr/include/g++/bits/stl_pair.h:276:5: note:   template argument deduction/substitution failed:
/usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2/src/ops/sort.cpp:147:68: note:   cannot convert 'iter.__gnu_cxx::__normal_iterator<_Iterator, _Container>::operator*<OpenBabel::OBBase**, std::vector<OpenBabel::OBBase*> >()' (type 'OpenBabel::OBBase*') to type 'OpenBabel::OBBase*&&'
       valvec.push_back(std::make_pair<OBBase*,std::string>(*iter, s));
                                                                    ^
*** Error code 1

Stop.
make[2]: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make: stopped in /usr/pkgsrc/biology/openbabel/work/openbabel-2.3.2
*** Error code 1

Stop.
make[2]: stopped in /usr/pkgsrc/biology/openbabel
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/biology/openbabel
*** Error code 1

Stop.
make: stopped in /usr/pkgsrc/wip/molsketch

```
:(

**Comment by krytarowski** [comment]
Please upgrade pkgsrc/biology/openbabel and try to build it.

I will need to try to patch molsketch to build against it.

**Comment by voidpin** [comment]
Ok, will do!
Should I try to upgrade to 3.0.0 or 2.4.1?

**Comment by krytarowski** [comment]
pkgsrc/biology/openbabel is upgraded now to 3.0.0

I am trying to build molsketch with it.

Please try to build pkgsrc openbabel version 3.0.0.

**Comment by krytarowski** [comment]
OK: pkgsrc/biology/openbabel 3.0.0nb1
+ molsketch from pkgsrc-wip work for me

```
commit 9a725bc110e331bbf46df8fca3b71e5b28bc43c0 (HEAD -> master, origin/master, origin/HEAD)
Author: Kamil Rytarowski <n54@gmx.com>
Date:   Wed Nov 20 19:06:06 2019 +0100

    molsketch: Fix build with openbabel 3.0.0
```

I have ported it to openbabel.

Please build openbabel 3.0.0nb1 and the newest version of molsketch.

**Comment by voidpin** [comment]
Thank you so much for this!
I'll give it a go again tomorrow morning with openbabel 3.0.0 from pkgsrc-HEAD and report back.

**Comment by voidpin** [comment]
@krytarowski maybe I'm doing something wrong :(
I've rm -r pkgsrc/, cloned the git-repo of pkgsrc-HEAD, followed by pkgsrc-wip. Everything built and installed until this point...
```

=> Bootstrap dependency digest>=20010302: found digest-20190127
===> Patching for molsketch-0.6.0
=> Applying pkgsrc patches for molsketch-0.6.0
**************************************
Ignoring patch file /usr/pkgsrc/wip/molsketch/patches/patch-CMakeLists.txt: invalid checksum
**************************************
Ignoring previously applied (or reversed) patch.
1 out of 1 hunks ignored--saving rejects to cmake/modules/FindOpenBabel2.cmake.rej
Patch /usr/pkgsrc/wip/molsketch/patches/patch-cmake_modules_FindOpenBabel2.cmake failed
Ignoring previously applied (or reversed) patch.
3 out of 3 hunks ignored--saving rejects to obabeliface/obabeliface.cpp.rej
Patch /usr/pkgsrc/wip/molsketch/patches/patch-obabeliface_obabeliface.cpp failed
ERROR: Patching failed due to modified or broken patch file(s):
ERROR:  /usr/pkgsrc/wip/molsketch/patches/patch-CMakeLists.txt
ERROR:  /usr/pkgsrc/wip/molsketch/patches/patch-cmake_modules_FindOpenBabel2.cmake
ERROR:  /usr/pkgsrc/wip/molsketch/patches/patch-obabeliface_obabeliface.cpp
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/wip/molsketch
*** Error code 1

Stop.
make: stopped in /usr/pkgsrc/wip/molsketch

```

**Comment by krytarowski** [comment]
Please update pkgsrc-wip and retry. I have regenerated the checksum.

**Comment by voidpin** [comment]
Just saw you had pushed an update :) Cheers!!
I'm out this evening ;), but I'll re-build it asap (I can).

**Comment by voidpin** [comment]
@krytarowski It works! Thank you very much!!!!
The program work fine and let me tell you, its probably the best open source molecule editor I've tried. Thanks!!!!
![2019-11-22-140124_1600x900_scrot](https://user-images.githubusercontent.com/35956139/69427996-85a51000-0d30-11ea-9be8-4356884261be.png)

**Comment by krytarowski** [comment]
OK, so homework:

 - please get in touch with openbabel people and upstream patches for it in pkgsrc

* fix .pc file not upgraded since openbabel2
* add missing includes for `std::sort` (`<algorithm>`)

 - please get in touch with molsketch people and upstream patches for new openbabel

**Comment by voidpin** [comment]
Ok, I've dropped a message to openbabel and molsketch people and waiting an answer.
The other,

   ```
fix .pc file not upgraded since openbabel2
add missing includes for std::sort (<algorithm>)
```
I'm not sure what you're asking me to do??

**Comment by krytarowski** [comment]
That was a comment what is done by the patches, to be forwarded to upstream.

**Comment by voidpin** [comment]
Pull-request for Molesketch, https://github.com/hvennekate/Molsketch/pull/4
Working on the one for openbabel sooooon....

**Comment by voidpin** [comment]
#2093 merged into master for openbabel ;)

**Comment by voidpin** [comment]
@krytarowski 
Can `Molsketch` be merged?

**Comment by krytarowski** [comment]
I prefer to do it after merging local patches into Molsketch and releasing a new version of Molsketch, so pkgsrc will ship with 0 local patches.

**Comment by voidpin** [comment]
Fair enough, I agree with that. Its for sure cleaner.
