### ISSUE TITLE
Trying to package qt5ct

### ISSUE THREAD

**Issue by voidpin** [NetBSD/pkgsrc-wip#16]
Hi folks,
After the great help from @krytarowski packaging molsketch, I've decided to try one on my own.
I'm trying to package qt5ct (https://sourceforge.net/projects/qt5ct), but I can't figure what I'm doing wrong!?
Here's my Makefile so far,
```

# $NetBSD$

DISTNAME=	qt5ct-0.41
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=qt5ct/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	voidpin@protonmail.com
HOMEPAGE=	https://sourceforge.net/projects/qt5ct/files/qt5ct-0.41.tar.bz2
COMMENT=	Tool for customizing Qt5-apps outside KDE
LICENSE=	2-clause-bsd

TOOL_DEPENDS+=	qt5-qttools-[0-9]*:../../x11/qt5-qttools

USE_CMAKE=	yes
USE_TOOLS=	pkg-config

USE_LANGUAGES=	c c++

.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"

```

and here's the error I'm getting,

```
=> Tool dependency qt5-qttools-[0-9]*: found qt5-qttools-5.13.1nb1
=> Tool dependency glib2-tools-[0-9]*: found glib2-tools-2.62.2
=> Tool dependency pkgconf-[0-9]*: found pkgconf-1.6.0
=> Build dependency x11-links>=1.30: found x11-links-1.30
=> Build dependency cwrappers>=20150314: found cwrappers-20180325
=> Full dependency qt5-qtbase>=5.13.1: found qt5-qtbase-5.13.1
=> Full dependency qt5-qtsvg>=5.13.1: found qt5-qtsvg-5.13.1
===> Overriding tools for qt5ct-0.41
===> Extracting for qt5ct-0.41
bzcat: /usr/pkgsrc/distfiles//qt5ct-0.41.tar.bz2 is not a bzip2 file.
tar: End of archive volume 1 reached
tar: Sorry, unable to determine archive format.
*** Error code 1

Stop.

```

Why?!
`EXTRACT_SUFX=	.tar.bz2` and the file is `qt5ct-0.41.tar.bz2`. Any thoughts or hints?
TIA

**Comment by voidpin** [comment]
Found the error, just had to look carefully :)
```
# $NetBSD$
...
EXTRACT_SUFX=	.tar.bz2
...
HOMEPAGE=	https://sourceforge.net/projects/qt5ct/files/qt5ct-0.41.tar.bz2
COMMENT=	Tool for customizing Qt5-apps outside KDE
LICENSE=	2-clause-bsd

TOOL_DEPENDS+=	qt5-qttools-[0-9]*:../../x11/qt5-qttools
...

```
The build starts, but packaging `qt5` stuff looks rather complex to me right now :(
I might get back to this once I get more comfortable.

**Comment by krytarowski** [comment]
`EXTRACT_USING=bsdtar`

**Comment by voidpin** [comment]
So, I've managed to make it work and it's now installed on my system and I can theme my Qt5-apps with it.
![2019-11-28-143249_1600x900_scrot](https://user-images.githubusercontent.com/35956139/69812193-e1b7da80-11ef-11ea-9569-0284593954fd.png)

But, I'm still missing something?!!
Here's my current Makefile
```
# $NetBSD$

DISTNAME=	qt5ct-0.41
PKGNAME=	${DISTNAME}
CATEGORIES=	x11	
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=qt5ct/}	
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	voidpin@protonmail.com	
HOMEPAGE=	https://sourceforge.net/projects/qt5ct/files/
COMMENT=	Tool for customizing Qt5-apps outside KDE	
LICENSE=	2-clause-bsd	

USE_TOOLS=	pkg-config
USE_LANGUAGES=	c c++
QMAKE=		${PREFIX}/qt5/bin/qmake
CMAKE_ENV+=     PATH="$$PATH":${PREFIX}/qt5/bin
CONFIGURE_ENV+= PATH="$$PATH":${PREFIX}/qt5/bin
CONFIGURE_ENV+= QMAKE=${QMAKE}
CMAKE_ENV+=     QMAKE=${QMAKE}
CMAKE_ARGS+=    -D QMAKE:PATH=${QMAKE}
CMAKE_ARGS+=    -D PATH:STRING="$$PATH":${PREFIX}/qt5/bin
CONFIGURE_ARGS+=QMAKE=${QMAKE}

TOOL_DEPENDS+=	qt5-qttools-[0-9]*:../../x11/qt5-qttools

USE_LANGUAGES=	c++

.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"

```
When all dependencies are done I have to do the following from `/usr/pkgsrc/wip/qt5ct`
```
cd work/qt5ct
/usr/pkg/qt5/bin qmake
cd ..
cd ..
make
doas make install

```
Obviously, I'd like to skip the manual intervention. Any pro tips from anyone more experienced?

**Comment by krytarowski** [comment]
grep other packages how to use qmake/QMAKE.

**Comment by voidpin** [comment]
Still no luck :(
I can still `cd` into `work/qt5ct`, run `/usr/pkg/qt5/bin/qmake` to generate the Makefile, return to `/usr/pkgsrc/wip/qt5ct` and run `make`. Then it works, but not without doing this.

#Makefile
```
# $NetBSD$

DISTNAME=	qt5ct-0.41
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=qt5ct/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	voidpin@protonmail.com
HOMEPAGE=	https://sourceforge.net/projects/qt5ct/files/
COMMENT=	Tool for customizing Qt5-apps outside KDE
LICENSE=	2-clause-bsd

USE_TOOLS=	pkg-config
USE_LANGUAGES=	c c++

MAKE_ENV=	QTPREFIX=${QTPREFIX:Q}
QMAKE=		${QTPREFIX}/bin/qmake
CONFIGURE_ENV+=	QMAKE=${QMAKE}
CONFIGURE_ARGS+=QMAKE=${QMAKE}

TOOL_DEPENDS+=	qt5-qttools-[0-9]*:../../x11/qt5-qttools

.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"

```

**Comment by krytarowski** [comment]
Keep grepping, there should be a pre-configure: step or similar.

**Comment by voidpin** [comment]
@krytarowski 
Thx for believing and sorry for the delay, I've been busy at work!!
Success!!
```
# $NetBSD$

DISTNAME=		qt5ct-0.41
CATEGORIES=		x11
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=qt5ct/}
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		voidpin@protonmail.com
HOMEPAGE=		https://sourceforge.net/projects/qt5ct/files/
COMMENT=		Tool for customizing Qt5-apps outside KDE
LICENSE=		2-clause-bsd

USE_TOOLS=		pkg-config
USE_LANGUAGES=		c c++

WRKSRC=         	${WRKDIR}/${DISTNAME}

QTDIR=			/usr/pkg/qt5
MAKE_ENV+=		QTPREFIX=${QTDIR}
QMAKE=			${QTPREFIX}/bin/qmake
CONFIGURE_ENV+=		QMAKE=${QMAKE}
CONFIGURE_ARGS+= 	QMAKE

do-configure:
	(cd ${WRKSRC} && ${QTDIR}/bin/qmake -o Makefile)

TOOL_DEPENDS+=		qt5-qttools-[0-9]*:../../x11/qt5-qttools

.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"

```
Only one but...
It installs the package into `/usr/bin` and not into `/usr/pkg/bin` as it should on NetBSD.

Should I push it into wip?! Or, can you give me a hint on how to fix the install path!?

**Comment by krytarowski** [comment]
Just commit it and I can have a look.

**Comment by voidpin** [comment]
I had to create a new ssh key and I'm still waiting to get commit access.
I could do a pull request, if this is acceptabel?

**Comment by krytarowski** [comment]
This patch fixes build for me:

http://netbsd.org/~kamil/patch-00205-qt5ct.txt

Please apply to pkgsrc-wip.

**Comment by voidpin** [comment]
Thanks!
I'll build the package once again tomorrow and commit the changes.
Still have a lot to learn, but all your changes made sense now and I won't give up.
Although, this might be the last thing I will commit for some time to come.
I'm curious about the work from @niacat on `wayland` and I might try to build a wayland-NetBSD desktop during the coming week :)

**Comment by voidpin** [comment]
@krytarowski 
Fixed! Everything works as fine.
Feel free to import the package to pkgsrc main branch.
Thx!

**Comment by krytarowski** [comment]
Imported to pkgsrc/x11/qt5ct.

**Comment by voidpin** [comment]
@krytarowski 
Thank you!
