### ISSUE TITLE
Some gdb-netbsd patches can be dropped

### ISSUE THREAD

**Issue by cbiesinger** [NetBSD/pkgsrc-wip#17]
I was looking through https://github.com/NetBSD/pkgsrc-wip/tree/master/gdb-netbsd/patches and noticed some patches there are not necessary (anymore)

First, there are a number of 0 byte patches, which can be easily deleted.

Then, patch-gdb_p-exp.y is not necessary anymore as of gdb revision 8aae434443d, which also sets type to NULL.
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blobdiff;f=gdb/p-exp.y;h=9e2dc829d7ff332ee6603a24f60b5cc6757174e1;hp=c214cf1aa909b6cab07a39a6171747e2a7fd3834;hb=8aae434443d;hpb=819843c7029916120aa2929f80e0d7276177a7fb

Then, some patches only change comments, sometimes adding typos:

patch-bfd_netbsd-core.c
patch-gdb_ppc-nbsd-tdep.c
patch-gdb_ppc-nbsd-tdep.h

And this patch enables some debug output, not clear if this is necessary?
patch-gdb_gdbserver_debug.c

**Comment by krytarowski** [comment]
Hello,

Thank you!

I will take care of the changes.

> patch-gdb_gdbserver_debug.c

It was useful to enable during development. Unfortunately Linux internals are..... well difficult and handling correct behavior of gdbserver backend required adding hacks emulating Linux bugs..

**Comment by krytarowski** [comment]
Changes merged.

**Comment by Blopez10** [comment]
So it’s fine now
