### ISSUE TITLE
gdb: patch-gdb_arm-nbsd-tdep.c is probably incorrect

### ISSUE THREAD

**Issue by cbiesinger** [NetBSD/pkgsrc-wip#18]
cc @krytarowski 

https://github.com/NetBSD/pkgsrc-wip/blob/master/gdb-netbsd/patches/patch-gdb_arm-nbsd-tdep.c

The patch calls:
```
+  set_gdbarch_iterate_over_regset_sections
+    (gdbarch, armbsd_iterate_over_regset_sections);
```

However, that function seems to assume the FPA architecture for floating point registers:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/arm-bsd-tdep.c;h=8cef77297bba2a28385b9647e44ac7f3768d60ca;hb=69ed9b74b61359d43a6f5f5a295c3cfb7f3ee61c#l49
(it doesn't use `ARM_D0_REGNUM`, etc.).

Also, I would assume (but don't know) that NetBSD core files store FP registers as a struct fpreg, which does not match the layout assumed by that function.

**Comment by cbiesinger** [comment]
I looked into this a bit more...

As far as I can tell, NetBSD-arm does not write a fp register section to the core file? Or did I do something wrong?

Anyway, for VFP register handling to really work, the netbsd target needs to return the right target description:
- arm_netbsd_nat_target should override read_description and return something like `arm_read_description (ARM_FP_TYPE_VFPV2);`, depending on what is supported by the CPU
- arm-nbsd-tdep should implement a gdbarch method core_read_description which does something similar based on what is in the core file (see other places that call `set_gdbarch_core_read_description`, e.g. arm-linux-tdep.c)

Otherwise, things like "info all-registers" will not show the VFP registers.

**Comment by krytarowski** [comment]
Thank you. We have added this to our TODO queue. Once we will be done with x86 and aarch64 we will be back to this.

**Comment by cbiesinger** [comment]
> arm_netbsd_nat_target should override read_description and return something like 
> `arm_read_description (ARM_FP_TYPE_VFPV2);`, depending on what is supported by the CPU

This is now fixed upstream:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=81b86b9702b5be9d022e9b0c96c1ee2ce339b5b9

However, the corefile-related stuff is not fixed.

**Comment by krytarowski** [comment]
Thank you!

**Comment by cbiesinger** [comment]
https://sourceware.org/ml/gdb-patches/2020-03/msg00153.html implements `iterate_over_regset_sections` for arm-netbsd in a better way, however it still does not handle floating point registers, which I did not see written to corefiles.

Also I did notice that the aarch64 patch does handle this apparently correctly.

**Comment by 0-wiz-0** [comment]
I guess this is fixed now. If not, please discuss it on the mailing lists. Thanks.
