### ISSUE TITLE
ImportError: No module named libvirt

### ISSUE THREAD

**Issue by Marietto2008** [NetBSD/pkgsrc-wip#21]
Hello.

I've just installed virt-manager with pkgin. Everything went ok. But,when I ran it,an error came up :

```
netbsd-marietto# virt-manager


Traceback (most recent call last):

File "/usr/pkg/share/virt-manager/virt-manager.py", line 386, in <module>

main()

File "/usr/pkg/share/virt-manager/virt-manager.py", line 247, in main

from virtManager import cli

File "/usr/pkg/share/virt-manager/virtManager/cli.py", line 29, in <module>

import libvirt

ImportError: No module named libvirt
```

Googling a little bit maybe I've found the solution here :

https://www.unitedbsd.com/d/285-linux-user-and-netbsd-enthusiast-hoping-to-migrate-some-day

where "kim" said :

Looking at pkgsrc/sysutils/libvirt/PLIST it doesn't look like the package provides any Python bindings -- which is what the "ImportError: No module named libvirt" error message is about. You could try py-libvirt from pkgsrc-wip and see how that works out.

I tried,but it didn't work :

```
netbsd-marietto# cd py-libvirt

netbsd-marietto# ls

DESCR Makefile PLIST distinfo distinfo.25058

netbsd-marietto# make

make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 15: Need an operator

make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 16: Need an operator

make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 17: Need an operator

make: Fatal errors encountered -- cannot continue

make: stopped in /home/mario/Desktop/pkgsrc-wip/py-libvirt

```

**Comment by Marietto2008** [comment]
gedit /home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile

# $NetBSD: Makefile,v 1.32 2018/11/30 09:59:40 adam Exp $

PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/-python//}
DISTNAME=	libvirt-python-5.8.0
CATEGORIES=	sysutils python
MASTER_SITES=	https://libvirt.org/sources/python/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://libvirt.org/sources/python/
COMMENT=	libvirt python library
LICENSE=	gnu-lgpl-v2

USE_TOOLS+=	pkg-config

# .include "../../wip/libvirt/buildlink3.mk"
# .include "../../lang/python/distutils.mk"
# .include "../../mk/bsd.pkg.mk"

 .include "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk"
 .include "/usr/pkgsrc/lang/python/distutils.mk"
 .include "/usr/pkgsrc/mk/bsd.pkg.mk"

netbsd-marietto# make

make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 19: Need an operator
make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 20: Need an operator
make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 21: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /home/mario/Desktop/pkgsrc-wip/py-libvirt

**Comment by he32** [comment]
>  .include "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk"
>  .include "/usr/pkgsrc/lang/python/distutils.mk"
>  .include "/usr/pkgsrc/mk/bsd.pkg.mk"

Don't those lines need to start from coloumn 0?

- Håvard

**Comment by Marietto2008** [comment]
netbsd-marietto# make

make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 11: Could not find ../../security/gnutls/buildlink3.mk
make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 12: Could not find ../../textproc/libxml2/buildlink3.mk
make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 13: Could not find ../../devel/yajl/buildlink3.mk
make: "/usr/pkgsrc/mk/bsd.fast.prefs.mk" line 7: Could not find ../../mk/bsd.prefs.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 377: Cannot open /mk/defaults/mk.conf
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 395: Cannot open /mk/platform/NetBSD.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 636: Cannot open /mk/tools/defaults.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 638: Malformed conditional (${FETCH_USING} == "auto")
sh: 1: Syntax error: end of file unexpected
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 651: warning: "cd  && " returned non-zero status
sh: 1: Syntax error: end of file unexpected
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 671: warning: "cd /home/mario/Desktop/pkgsrc-wip/py-libvirt && " returned non-zero status
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 721: Malformed conditional (${PKGSRC_MKPIE:tl} == "yes" &&  ${MKPIE_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_MKPIE:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 731: Malformed conditional (${PKGSRC_MKREPRO:tl} == "yes" &&  ${MKREPRO_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_MKREPRO:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 742: Malformed conditional (${PKGSRC_USE_FORTIFY:tl} != "no" &&  ${FORTIFY_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_FORTIFY:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 753: Malformed conditional (${PKGSRC_USE_RELRO:tl} != "no" &&  ${RELRO_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_RELRO:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 765: Malformed conditional (${PKGSRC_USE_SSP:tl} != "no" &&  ${SSP_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_SSP:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 776: Malformed conditional (${PKGSRC_USE_STACK_CHECK:tl} != "no" &&  ${STACK_CHECK_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_STACK_CHECK:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 800: Malformed conditional (empty(PKGPATH:Mpkgtools/cwrappers) &&  (${USE_CWRAPPERS:tl} == "yes" ||  (${USE_CWRAPPERS:tl} == "auto" &&  ${_OPSYS_SUPPORTS_CWRAPPERS:Uno} == "yes")))
make: "/usr/pkgsrc/mk/wrapper/wrapper-defs.mk" line 33: Malformed conditional (${_USE_CWRAPPERS} == "yes")
sh: /usr/lib/libpthread.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libpthread.*`" != "/usr/lib/libpthread.*"; then   yes;                                                 else                                                             no;                                            fi" returned non-zero status
sh: /usr/lib/libc_r.*: not found
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libc_r.*`" != "/usr/lib/libc_r.*"; then   yes;                                                 else                                                             no;                                            fi" returned non-zero status
sh: /usr/lib/librt.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/librt.*`" != "/usr/lib/librt.*"; then   yes;                                           else                                                             no;                                            fi" returned non-zero status
make: "/usr/pkgsrc/mk/dlopen.builtin.mk" line 9: Could not find ../../mk/buildlink3/bsd.builtin.mk
sh: /usr/lib/libintl.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libintl.*`" != "/usr/lib/libintl.*"; then   yes;                                               else                                                             no;                                            fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q \#define\[\ \       \]\*__USE_GNU_GETTEXT /usr/include/libintl.h; then        /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q gentoo-multilib/.\*/libintl.h /usr/include/libintl.h; then    /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q char.\*ngettext /usr/include/libintl.h; then          /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q libgnuintl.h /usr/include/libintl.h; then     /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
make: "/usr/pkgsrc/mk/check/bsd.check-vars.mk" line 22: Malformed conditional (${_OPSYS_CAN_CHECK_SHLIBS:tl} == "yes")
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 129: warning: " -n -u" returned non-zero status
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 132: warning: " -n -g" returned non-zero status
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 135: warning: " -n -G" returned non-zero status
make: "/usr/pkgsrc/mk/bsd.pkg.mk" line 426: Malformed conditional (${_USE_CWRAPPERS} == "yes")
sh: /pkg_admin: not found
sh: /pkg_admin: not found
make: "${PKG_TOOLS_BIN}/pkg_admin -K ${_CROSS_DESTDIR}/usr/pkg/pkgdb config-var PKGVULNDIR" returned non-zero status
make: Fatal errors encountered -- cannot continue
make: stopped in /home/mario/Desktop/pkgsrc-wip/py-libvirt

**Comment by he32** [comment]
> netbsd-marietto# make
>
> make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 11: Could not find ../../security/gnutls/buildlink3.mk
> make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 12: Could not find ../../textproc/libxml2/buildlink3.mk
> make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 13: Could not find ../../devel/yajl/buildlink3.mk
> make: "/usr/pkgsrc/mk/bsd.fast.prefs.mk" line 7: Could not find ../../mk/bsd.prefs.mk
> make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 377: Cannot open /mk/defaults/mk.conf
> make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 395: Cannot open /mk/platform/NetBSD.mk

etc. etc. etc.

Have you manually messed with ${_PKGSRC_TOPDIR}?  "Don't do that!"
The leading underscore in the variable name is an indication that this
is a private variable for the pkgsrc mk implementation, and thus not a
variable the user is expected to tweak.  The construct in
mk/bsd.prefs.mk which includes mk/defaults/mk.conf looks like this:

.include "${_PKGSRC_TOPDIR}/mk/defaults/mk.conf"

and your make invocation seems to think that ${_PKGSRC_TOPDIR} is the
empty string, which it most certainly should not be.

Regards,

- Håvard

**Comment by Marietto2008** [comment]
No. The only thing that I did has been to comment these lines 👍 

```
 .include "../../wip/libvirt/buildlink3.mk"
 .include "../../lang/python/distutils.mk"
 .include "../../mk/bsd.pkg.mk"
```

because if I don't do  that,I get the following error :

```
netbsd-marietto# make
make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 15: Need an operator
make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 16: Need an operator
make: "/home/mario/Desktop/pkgsrc-wip/py-libvirt/Makefile" line 17: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /home/mario/Desktop/pkgsrc-wip/py-libvirt
```

**Comment by 0-wiz-0** [comment]
The pkgsrc-wip repository needs to be checked out as "wip" and put into /usr/pkgsrc (or wherever the rest of your pkgsrc checkout is).
I've just successfully built the wip/virt-manager package on NetBSD-9.99.88/amd64 (after fixing some minor issues in it and its dependencies). Make sure you have the latest pkgsrc-wip tree.

We do not use github issues, please use the pkgsrc-users@NetBSD.org mailing list instead.

**Comment by Marietto2008** [comment]
I've already bootstrapped the pkgsrc. They are in /home/marietto/Desktop/pkgsrc-wip folder. Infact I have exchanged the paths stored in the Makefile with these :

```
.include "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk"
.include "/usr/pkgsrc/lang/python/distutils.mk"
.include "/usr/pkgsrc/mk/bsd.pkg.mk"
```

but I get the folowing situation :

```
netbsd-marietto# make

make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 11: Could not find ../../security/gnutls/buildlink3.mk
make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 12: Could not find ../../textproc/libxml2/buildlink3.mk
make: "/home/mario/Desktop/pkgsrc-wip/libvirt/buildlink3.mk" line 13: Could not find ../../devel/yajl/buildlink3.mk
make: "/usr/pkgsrc/mk/bsd.fast.prefs.mk" line 7: Could not find ../../mk/bsd.prefs.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 377: Cannot open /mk/defaults/mk.conf
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 395: Cannot open /mk/platform/NetBSD.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 636: Cannot open /mk/tools/defaults.mk
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 638: Malformed conditional (${FETCH_USING} == "auto")
sh: 1: Syntax error: end of file unexpected
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 651: warning: "cd  && " returned non-zero status
sh: 1: Syntax error: end of file unexpected
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 671: warning: "cd /home/mario/Desktop/pkgsrc-wip/py-libvirt && " returned non-zero status
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 721: Malformed conditional (${PKGSRC_MKPIE:tl} == "yes" &&  ${MKPIE_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_MKPIE:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 731: Malformed conditional (${PKGSRC_MKREPRO:tl} == "yes" &&  ${MKREPRO_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_MKREPRO:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 742: Malformed conditional (${PKGSRC_USE_FORTIFY:tl} != "no" &&  ${FORTIFY_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_FORTIFY:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 753: Malformed conditional (${PKGSRC_USE_RELRO:tl} != "no" &&  ${RELRO_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_RELRO:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 765: Malformed conditional (${PKGSRC_USE_SSP:tl} != "no" &&  ${SSP_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_SSP:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 776: Malformed conditional (${PKGSRC_USE_STACK_CHECK:tl} != "no" &&  ${STACK_CHECK_SUPPORTED:Uyes:tl} == "yes" &&  ${_OPSYS_SUPPORTS_STACK_CHECK:Uno} == "yes")
make: "/usr/pkgsrc/mk/bsd.prefs.mk" line 800: Malformed conditional (empty(PKGPATH:Mpkgtools/cwrappers) &&  (${USE_CWRAPPERS:tl} == "yes" ||  (${USE_CWRAPPERS:tl} == "auto" &&  ${_OPSYS_SUPPORTS_CWRAPPERS:Uno} == "yes")))
make: "/usr/pkgsrc/mk/wrapper/wrapper-defs.mk" line 33: Malformed conditional (${_USE_CWRAPPERS} == "yes")
sh: /usr/lib/libpthread.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libpthread.*`" != "/usr/lib/libpthread.*"; then   yes;                                                 else                                                             no;                                            fi" returned non-zero status
sh: /usr/lib/libc_r.*: not found
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libc_r.*`" != "/usr/lib/libc_r.*"; then   yes;                                                 else                                                             no;                                            fi" returned non-zero status
sh: /usr/lib/librt.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/librt.*`" != "/usr/lib/librt.*"; then   yes;                                           else                                                             no;                                            fi" returned non-zero status
make: "/usr/pkgsrc/mk/dlopen.builtin.mk" line 9: Could not find ../../mk/buildlink3/bsd.builtin.mk
sh: /usr/lib/libintl.a: permission denied
sh: : not found
sh: no: not found
make: "/usr/pkgsrc/mk/buildlink3/find-libs.mk" line 65: warning: "if  "` /usr/lib/libintl.*`" != "/usr/lib/libintl.*"; then   yes;                                               else                                                             no;                                            fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q \#define\[\ \       \]\*__USE_GNU_GETTEXT /usr/include/libintl.h; then        /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q gentoo-multilib/.\*/libintl.h /usr/include/libintl.h; then    /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q char.\*ngettext /usr/include/libintl.h; then          /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
sh: -q: not found
sh: __nonexistent__: not found
make: "/usr/pkgsrc/mk/buildlink3/find-headers.mk" line 92: warning: "if  -q libgnuintl.h /usr/include/libintl.h; then     /usr/include/libintl.h;                                else                                                             __nonexistent__;                               fi" returned non-zero status
make: "/usr/pkgsrc/mk/check/bsd.check-vars.mk" line 22: Malformed conditional (${_OPSYS_CAN_CHECK_SHLIBS:tl} == "yes")
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 129: warning: " -n -u" returned non-zero status
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 132: warning: " -n -g" returned non-zero status
sh: -n: not found
make: "/usr/pkgsrc/mk/unprivileged.mk" line 135: warning: " -n -G" returned non-zero status
make: "/usr/pkgsrc/mk/bsd.pkg.mk" line 426: Malformed conditional (${_USE_CWRAPPERS} == "yes")
sh: /pkg_admin: not found
sh: /pkg_admin: not found
make: "${PKG_TOOLS_BIN}/pkg_admin -K ${_CROSS_DESTDIR}/usr/pkg/pkgdb config-var PKGVULNDIR" returned non-zero status
make: Fatal errors encountered -- cannot continue
make: stopped in /home/mario/Desktop/pkgsrc-wip/py-libvirt


```

**Comment by 0-wiz-0** [comment]
Please use the mailing list, as I said above.

You need to get a checkout of pkgsrc in source form, e.g. in /home/marietto/Desktop/pkgsrc; then you need to put the checkout of the wip repository at /home/marietto/Desktop/pkgsrc/wip.

The bootstrap destination is for the binaries, not the sources. If you bootstrapped into /home/marietto/Desktop/pkgsrc-wip you will find your binaries in /home/marietto/Desktop/pkgsrc-wip/bin

You still need the pkgsrc sources separately (see above).
