### ISSUE TITLE
LLVM 6 toolchain

### ISSUE THREAD

**Issue by kasper3** [NetBSD/pkgsrc-wip#6]
http://llvm.org/
LLVM 6 toolchain (containing clang, lldb and llvm-libunwind etc.) was released in March, with some interesting WebAssembly improvements. Would it be possible to port it in Q2?

**Comment by 0-wiz-0** [comment]
llvm is in pkgsrc itself, and pkgsrc uses gnats. (http://gnats.netbsd.org)
llvm-6.0 is already noted in `pkgsrc/doc/TODO`, I hope someone will do the update sooner rather than later.

**Comment by kasper3** [comment]
> llvm is in pkgsrc itself

Could this issue be then opened at https://github.com/NetBSD/pkgsrc/issues for progress tracking?

**Comment by krytarowski** [comment]
Upgrades aren't that simple, we need to rebase projects using it. This means that we aren't in rush.
